return {
  -- "williamboman/mason.nvim",
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "black",
      "bash-language-server",
      "blade-formatter",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-ls",
      "html-lsp",
      "nginx-language-server",
      "pyright",
      -- "astro-language-server", this for astro
      "emmet-language-server",
      "eslint-lsp",
      -- "gofumpt", this for golang language
      -- "goimports",
      -- "gopls",
      "intelephense",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "php-cs-fixer",
      "phpcs",
      "pint",
      "prettier",
      "shfmt",
      -- "sleek", this for svelte
      "sqlfluff",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "vtsls",
    },
  },
}
